name: beanstalk-deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Copy production env
      run: 'echo -e "${{secrets.ENV}}" > .env'
              
    - name: Config yarn
      run: |
        npm i -g yarn
        echo -e "machine github.com\nlogin ${{ secrets.GH_TOKEN }}\npassword x-oauth-basic" > $HOME/.netrc
        chmod 600 $HOME/.netrc
        

    - name: Installing packages
      run: yarn install --network-concurrency 1
      
    - name: Building application
      run: yarn run build
      
    - name: Generate deployment package
      run: zip -r deploy.zip ./
      
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
    
    - name: Beanstalk Deploy for app
      uses: runningdeveloper/beanstalk-deploy@v11
      with:
         aws_access_key: "${{secrets.AWS_ACCESS_KEY}}"
         aws_secret_key: "${{secrets.AWS_SECRET_KEY}}"
         application_name: "Services"
         environment_name: "whatsapp"
         region: "ap-east-1"
         version_label: "${{ github.event.repository.name }}-${{ steps.format-time.outputs.replaced }}"
         region_specific_s3: "true"
         use_existing_version_if_available: "true"
         deployment_package: "deploy.zip"
